version: "3"

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
    labels:
      - "sparkle.app=api"

  web:
    restart: always
    build:
      context: .
      dockerfile: compose/django/Dockerfile
    depends_on:
      - db
    volumes:
      - ./src:/src
    expose:
      - "8000"
    env_file:
      - ./.envs/.django
    labels:
      - "sparkle.app=api"
    container_name: web

  db:
    build:
      context: .
      dockerfile: compose/postgres/Dockerfile
    env_file:
      - ./.envs/.postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    labels:
      - "sparkle.app=api"
