# Generated by Django 2.2.1 on 2019-12-07 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='quiz',
        ),
    ]
